KERNEL_TREE=/home/abelj1/rpi/raspberrypi-linux
CCPREFIX=/home/abelj1/tools/arm-bcm2708/arm-bcm2708-linux-gnueabi/bin/arm-bcm2708-linux-gnueabi-

obj-m += hello-1.o

all:
	make -C ${KERNEL_TREE} ARCH=arm CROSS_COMPILE=${CCPREFIX} M=$(PWD) modules





